=== chdd/IncompleteAutomataBasedModelChecking/IncompleteAutomataBasedModelChecking/src/test/resources/intersectionAutomaton.dtd
<!ELEMENT intersectionAutomaton (initialStates, states, acceptingStates,  transitionRelation, alphabet, transparentStates, mixedStates)>
  <!ELEMENT initialStates (initialState*)>
  <!ELEMENT states (state*)>
  <!ELEMENT acceptingStates (acceptingState*)>
  <!ELEMENT transparentStates (transparentState*)>
  <!ELEMENT mixedStates (mixedState*)>
  <!ELEMENT transitionRelation (element*)>
  <!ELEMENT alphabet (character*)>
  <!ELEMENT element (sourceState, transitions)>
  <!ELEMENT transitions (transition*)>
  <!ELEMENT transition (character, destinationState)>
  <!ELEMENT state EMPTY>
  <!ELEMENT mixedState (#PCDATA)>
  <!ELEMENT initialState (#PCDATA)>
  <!ELEMENT acceptingState (#PCDATA)>
  <!ELEMENT transparentState (#PCDATA)>
  <!ELEMENT destinationState (#PCDATA)>
  <!ELEMENT sourceState (#PCDATA)>
  <!ELEMENT character (#PCDATA)>
  <!ATTLIST state id CDATA #REQUIRED>

=== chdd/IncompleteAutomataBasedModelChecking/IncompleteAutomataBasedModelChecking/src/test/resources/IntersectionAutomaton1.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE intersectionAutomaton SYSTEM "intersectionAutomaton.dtd">
<intersectionAutomaton>
    <initialStates>
        <initialState>s1-s4-0</initialState>
    </initialStates>
    <states>
        <state id="s2-s5-0"/>
        <state id="s4-s4-0"/>
        <state id="s3-s6-0"/>
        <state id="s1-s4-0"/>
        <state id="s3-s6-2"/>
        <state id="s2-s4-0"/>
        <state id="s3-s5-1"/>
        <state id="s2-s6-0"/>
        <state id="s3-s6-1"/>
    </states>
    <acceptingStates>
        <acceptingState>s3-s6-2</acceptingState>
    </acceptingStates>
    <transitionRelation>
        <element>
            <sourceState id="s2-s5-0"/>
            <transitions>
                <transition>
                    <character>b</character>
                    <destinationState id="s2-s5-0"/>
                </transition>
                <transition>
                    <character>b</character>
                    <destinationState id="s3-s5-1"/>
                </transition>
                <transition>
                    <character>c</character>
                    <destinationState id="s2-s6-0"/>
                </transition>
            </transitions>
        </element>
        <element>
            <sourceState id="s4-s4-0"/>
            <transitions>
                <transition>
                    <character>b</character>
                    <destinationState id="s3-s5-1"/>
                </transition>
            </transitions>
        </element>
        <element>
            <sourceState id="s3-s6-0"/>
            <transitions>
                <transition>
                    <character>b</character>
                    <destinationState id="s3-s6-1"/>
                </transition>
            </transitions>
        </element>
        <element>
            <sourceState id="s1-s4-0"/>
            <transitions>
                <transition>
                    <character>a</character>
                    <destinationState id="s2-s4-0"/>
                </transition>
                <transition>
                    <character>a</character>
                    <destinationState id="s4-s4-0"/>
                </transition>
            </transitions>
        </element>
        <element>
            <sourceState id="s3-s6-2"/>
            <transitions>
                <transition>
                    <character>b</character>
                    <destinationState id="s3-s6-0"/>
                </transition>
            </transitions>
        </element>
        <element>
            <sourceState id="s2-s4-0"/>
            <transitions>
                <transition>
                    <character>b</character>
                    <destinationState id="s3-s5-1"/>
                </transition>
                <transition>
                    <character>a</character>
                    <destinationState id="s2-s4-0"/>
                </transition>
                <transition>
                    <character>b</character>
                    <destinationState id="s2-s5-0"/>
                </transition>
            </transitions>
        </element>
        <element>
            <sourceState id="s3-s5-1"/>
            <transitions>
                <transition>
                    <character>b</character>
                    <destinationState id="s3-s5-1"/>
                </transition>
            </transitions>
        </element>
        <element>
            <sourceState id="s2-s6-0"/>
            <transitions>
                <transition>
                    <character>a</character>
                    <destinationState id="s2-s6-0"/>
                </transition>
                <transition>
                    <character>b</character>
                    <destinationState id="s3-s6-1"/>
                </transition>
                <transition>
                    <character>c</character>
                    <destinationState id="s2-s6-0"/>
                </transition>
                <transition>
                    <character>b</character>
                    <destinationState id="s2-s6-0"/>
                </transition>
            </transitions>
        </element>
        <element>
            <sourceState id="s3-s6-1"/>
            <transitions>
                <transition>
                    <character>b</character>
                    <destinationState id="s3-s6-2"/>
                </transition>
            </transitions>
        </element>
    </transitionRelation>
    <alphabet>
        <character>b</character>
        <character>c</character>
        <character>a</character>
    </alphabet>
    <transparentStates/>
    <mixedStates>
        <mixedState>s2-s5-0</mixedState>
        <mixedState>s2-s4-0</mixedState>
        <mixedState>s2-s6-0</mixedState>
    </mixedStates>
</intersectionAutomaton>
