=== chdd/IncompleteAutomataBasedModelChecking/IncompleteAutomataBasedModelChecking/src/main/resources/automaton.dtd
<!ELEMENT buchiAutomaton (initialStates, states, acceptingStates,  transitionRelation, alphabet, transparentStates)>
  <!ELEMENT initialStates (initialState*)>
  <!ELEMENT states (state*)>
  <!ELEMENT acceptingStates (acceptingState*)>
  <!ELEMENT transparentStates (transparentState*)>
  <!ELEMENT transitionRelation (element*)>
  <!ELEMENT alphabet (character*)>
  <!ELEMENT element (sourceState, transitions)>
  <!ELEMENT transitions (transition*)>
  <!ELEMENT transition (character, destinationState)>
  <!ELEMENT state EMPTY>
  <!ELEMENT initialState (#PCDATA)>
  <!ELEMENT acceptingState (#PCDATA)>
  <!ELEMENT transparentState (#PCDATA)>
  <!ELEMENT destinationState (#PCDATA)>
  <!ELEMENT sourceState (#PCDATA)>
  <!ELEMENT character (#PCDATA)>
  <!ATTLIST state id CDATA #REQUIRED>

=== chdd/IncompleteAutomataBasedModelChecking/IncompleteAutomataBasedModelChecking/src/main/resources/Automaton2.xml
<?xml version="1.0"?>
<!DOCTYPE buchiAutomaton SYSTEM "automaton.dtd">
<buchiAutomaton>
    <initialStates>
        <initialState>s4</initialState>
    </initialStates>
    <states>
        <state id="s4"/>
        <state id="s5"/>
        <state id="s6"/>
    </states>
    <acceptingStates>
    	<acceptingState>s6</acceptingState>
    </acceptingStates>
   
    <transitionRelation>
        <element>
            <sourceState>s4</sourceState>
            <transitions>
            	 <transition>
                	<character>a</character>
                	<destinationState>s4</destinationState>
                </transition> 
                 <transition>
                	<character>b</character>
                	<destinationState>s5</destinationState>
                </transition> 
            </transitions>
        </element>
        <element>
            <sourceState>s5</sourceState>
            <transitions>
            	 <transition>
                	<character>b</character>
                	<destinationState>s5</destinationState>
                </transition> 
                <transition>
                	<character>c</character>
                	<destinationState>s6</destinationState>
                </transition> 
            </transitions>
        </element>
         <element>
            <sourceState>s6</sourceState>
            <transitions>
            	 <transition>
                	<character>a</character>
                	<destinationState>s6</destinationState>
                </transition>
            	 <transition>
                	<character>b</character>
                	<destinationState>s6</destinationState>
                </transition> 
                <transition>
                	<character>c</character>
                	<destinationState>s6</destinationState>
                </transition> 
            </transitions>
        </element>
    </transitionRelation>
    <alphabet>
        <character>a</character>
        <character>b</character>
        <character>c</character>
    </alphabet>
      <transparentStates>
    </transparentStates>
</buchiAutomaton>
